import { ref } from 'vue';
import { Learn } from './Learn';

export const U7_1 = ref<Learn[]>([
    { question: 'ära tooma, järele minema', answer: 'abholen' },
    { question: 'üksi', answer: 'allein' },
    { question: 'töötu', answer: 'Arbeitslose, der, -en' },
    { question: 'tööturg', answer: 'Arbeitsmarkt, der, "-e' },
    { question: 'töökoht', answer: 'Arbeitsplatz, der, "-e' },
    { question: 'tööaeg', answer: 'Arbeitszeit, die, -en' },
    { question: 'automehaanik', answer: 'Automechaniker/in, der/die, -/-nen' },
    { question: 'pagar', answer: 'Bäcker/in, der/die, -/-nen' },
    { question: 'pangaametnik', answer: 'Bankangestellte, der/die, -n' },
    { question: 'nõustama', answer: 'beraten' },
    { question: 'tööalaselt', answer: 'beruflich' },
    { question: 'tooma', answer: 'bringen' },
    { question: 'vend', answer: 'Bruder, der, "-' },
    { question: 'šanss', answer: 'Chance, die, -en' },
    { question: 'arvutiprogramm', answer: 'Computerprogramm, das, -e' },
    { question: 'asi, ese', answer: 'Ding, das, -e' },
    { question: 'sisse pakkima', answer: 'einpacken' },
    { question: 'vabrik', answer: 'Fabrik, die, -en' },
    { question: 'vaheaeg', answer: 'Ferien, die (Pl.)' },
    { question: 'telekat vaatama', answer: 'fernsehen' }
]);

export const U7_2 = ref<Learn[]>([
    { question: 'firma', answer: 'Firma, die, Firmen' },
    { question: 'jõusaal', answer: 'Fitness-Studio, das, -s' },
    { question: 'paindlik', answer: 'flexibel' },
    { question: 'lennupilet', answer: 'Flugticket, das, -s' },
    { question: 'lennuk', answer: 'Flugzeug, das, -e' },
    { question: 'sõbralik', answer: 'freundlich' },
    { question: 'juuksurisalong', answer: 'Friseursalon, der, -s' },
    { question: 'vara', answer: 'früh' },
    { question: 'raha', answer: 'Geld, das' },
    { question: 'juus', answer: 'Haar, das, -e' },
    { question: 'käelaba', answer: 'Hand, die, "-e' },
    { question: 'vihkama', answer: 'hassen' },
    { question: 'majapidamine', answer: 'Haushalt, der, -e' },
    { question: 'koduperenaine', answer: 'Hausfrau, die, -en' },
    { question: 'koduperemees', answer: 'Hausmann, der, "-er' },
    { question: 'informeerima, teavitama', answer: 'informieren' },
    { question: 'kaupmees', answer: 'Kauffrau, die, Kaufleute' },
    { question: 'kaupmees', answer: 'Kaufmann, der, Kaufleute' },
    { question: 'kelner/ ettekandja', answer: 'Kellner/in, der/die, -/-nen' },
    { question: 'lasteaed', answer: 'Kindergarten, der, "-en' }
]);

export const U7_3 = ref<Learn[]>([
    { question: 'kolleeg, töökaaslane', answer: 'Kollege/in, der/die, -n/-nen' },
    { question: 'medvend', answer: 'Krankenpfleger, der, -' },
    { question: 'medõde', answer: 'Krankenschwester, die, -n' },
    { question: 'klient', answer: 'Kunde/Kundin, der/die, -n/-nen' },
    { question: 'kerge, lihtne', answer: 'leicht' },
    { question: 'juhtima', answer: 'leiten' },
    { question: 'lahendus', answer: 'Lösung, die, -en' },
    { question: 'masin', answer: 'Maschine, die, -n' },
    { question: 'mehaanik', answer: 'Mechaniker/in, der/die, -/-nen' },
    { question: 'liige', answer: 'Mitglied, das, -er' },
    { question: 'ei iial', answer: 'nie' },
    { question: 'organiseerima, korraldama', answer: 'organisieren' },
    { question: 'patsient', answer: 'Patient/in, der/die, -en/-nen' },
    { question: 'planeerima', answer: 'planen' },
    { question: 'programmeerija', answer: 'Programmierer/in, der/die, -/-nen' },
    { question: 'parandama', answer: 'reparieren' },
    { question: 'broneerima', answer: 'reservieren' },
    { question: 'lõikama', answer: 'schneiden' },
    { question: 'kingas', answer: 'Schuh, der, -e' },
    { question: 'kingapood', answer: 'Schuhgeschäft, das, -e' }
]);

export const U7_4 = ref<Learn[]>([
    { question: 'istuma', answer: 'sitzen' },
    { question: 'poeg', answer: 'Sohn, der, "-e' },
    { question: 'statistika', answer: 'Statistik, die, -en' },
    { question: 'korras olema, klappima', answer: 'stimmen' },
    { question: 'see on õige/ tõsi', answer: 'das stimmt' },
    { question: 'tundide viisi', answer: 'stundenlang' },
    { question: 'otsimine, otsing', answer: 'Suche, die, -n' },
    { question: 'vahetama', answer: 'tauschen' },
    { question: 'taksojuht', answer: 'Taxifahrer/in, der/die, -/-nen' },
    { question: 'loom', answer: 'Tier, das, -e' },
    { question: 'tütar', answer: 'Tochter, die, "-' },
    { question: 'treener', answer: 'Trainer/in, der/die, -/-nen' },
    { question: 'trenn', answer: 'Training, das, -s' },
    { question: 'tegema', answer: 'tun' },
    { question: 'õpetama', answer: 'unterrichten' },
    { question: 'uurima', answer: 'untersuchen' },
    { question: 'teenima', answer: 'verdienen' },
    { question: 'müüma', answer: 'verkaufen' },
    { question: 'müüja', answer: 'Verkäufer/in, der/die, -/-nen' },
    { question: 'vähe', answer: 'wenig' },
    { question: 'töökoda', answer: 'Werkstatt, die, "-en' },
    { question: 'nädalavahetus', answer: 'Wochenende, das, -n' }
]);
